language: python
python:
  - 3.9

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/fabcohort_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDZmYjRjZjBiLWM3MzctNGNiZS1iYWVjLTViYTUyNTNjZTZlZAACEVsxLFsiZmFiY29ob3J0Il1dAAIsWzIsWyI1OTlhMDM1Yy01NDNkLTQxMjYtOWM2Ny01YzIxMjU1OTQzNTIiXV0AAAYgSmb5nsy9rqYTf-WbvqaFcUjR1wT-4qlsDM103tW0scw"
  on:
    branch: main